config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  get 'main/index'

  match 'main/help', to: 'main#help', via: 'get'

  get 'main/contacts'

  get 'main/about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @test = "Hello world!"
  end

  def help
  end

  def contacts
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Test1
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'shared/header'
    = yield
    = render 'shared/footer'

app/views/main/about.html.haml
%h1 Main#about
%p Find me in app/views/main/about.html.haml

app/views/main/contacts.html.haml
%h1 Main#contacts
%p Find me in app/views/main/contacts.html.haml

app/views/main/help.html.haml
%h1 Main#help
%p Find me in app/views/main/help.html.haml

app/views/main/index.html.haml
%h1 Main#index

%p
  =@test
%ul
  %li
    =link_to 'Contacts', main_contacts_path
  %li
    =link_to 'Help', main_help_path

app/views/shared/_footer.html.haml
%p
  ="Footer"

app/views/shared/_header.html.haml
%p
  ="Header"